import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Spartan&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className="bg-[#3a4764] max-w-[375px] h-screen">
        <nav className="navba grid grid-cols-3 text-white pt-7 ">
          <div className="font-black text-3xl pl-6">
            <h4 className="">calc</h4>
          </div>
          {/* <div className="">
            <h5 className="font-semibold text-right text-xs pt-7 pr-5">
              THEME
            </h5>
          </div>
          <div className="">
            <h1>123</h1>
            <h5 className="">. . .</h5>
         
          </div> */}
        </nav>
        <section className="output_bar text-white rounded-lg bg-[#182034] p-5 m-5  text-right font-bold text-3xl ">
          123456789
        </section>
        <section className="input_bar text-white rounded-lg bg-[#232c43] h-auto overflow-hidden m-5 ">
          <div className="p-7">
            <div className="grid grid-cols-4 grid-rows-5 grid-flow-row gap-7 justify-items-center">
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className=" font-black text-[#444b5a]  text-3xl pt-3">7</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className=" font-black text-[#444b5a] text-3xl pt-3">8</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className="  text-[#444b5a] font-black text-3xl pt-3">9</h1>
              </button>
              <button className="keys-blue h-16 w-16  bg-[#637097]  rounded-md  box-border">
                <h1 className="  text-white font-black text-md pt-2">DEL</h1>
              </button>

              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className=" font-black text-[#444b5a]  text-3xl pt-3">4</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className=" font-black text-[#444b5a] text-3xl pt-3">5</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className="  text-[#444b5a] font-black text-3xl pt-3">6</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className="  text-[#444b5a] font-black text-3xl pt-3">+</h1>
              </button>

              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className=" font-black text-[#444b5a]  text-3xl pt-3">1</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className=" font-black text-[#444b5a] text-3xl pt-3">2</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className="  text-[#444b5a] font-black text-3xl pt-3">3</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className="  text-[#444b5a] font-black text-3xl pt-3">-</h1>
              </button>

              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className=" font-black text-[#444b5a]  text-3xl pt-3">.</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className=" font-black text-[#444b5a] text-3xl pt-3">0</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className="  text-[#444b5a] font-black text-3xl pt-3">/</h1>
              </button>
              <button className="keys h-16 w-16 bg-[#eae3dc] rounded-md  box-border">
                <h1 className="  text-[#444b5a] font-black text-3xl pt-1">x</h1>
              </button>

              <button className="keys-blue h-16 w-[9rem]  bg-[#637097] rounded-md  box-border col-span-2">
                <h1 className="  text-white font-black text-md pt-2">RESET</h1>
              </button>

              <button className="keys-orange h-16 w-[9rem] bg-[#d03f2f] rounded-md  box-border col-span-2">
                <h1 className="  text-white font-black text-md pt-2"> = </h1>
              </button>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
